### ISSUE TITLE
It's just doesn't work for me

### ISSUE THREAD

**Issue by DD7-13** [Decimation/SmartImage#10]
![image](https://user-images.githubusercontent.com/43441620/102610183-ce9ae400-413d-11eb-85f1-ed7bb2660392.png)

**Comment by Decimation** [comment]
It looks like the image didn't upload. Are you using Imgur or ImgOps to upload?

**Comment by Xanawatt** [comment]
This is also confirmed happening to me as well. I use ImgOps

**Comment by Xanawatt** [comment]
I've tried using past versions as well so it must be a problem with how they changed how images gets uploaded

**Comment by Decimation** [comment]
Yeah, ImgOps changed how images are uploaded a while ago. I fixed it in a previous commit. The newest version will have this fixed.

**Comment by Decimation** [comment]
@Xanawatt @DD7-13 Try the newest release, v2.0. It includes the fix.

**Comment by Xanawatt** [comment]
there's no executable in the release unfortunately @Decimation

**Comment by Decimation** [comment]
Try now @Xanawatt

**Comment by Xanawatt** [comment]
yup, it works now! Thanks!
