### ISSUE TITLE
[IQDB] URL broken

### ISSUE THREAD

**Issue by Xanawatt** [Decimation/SmartImage#11]
the link appears like this when I do a search: 
![image](https://user-images.githubusercontent.com/22943944/102680686-7f2dd580-4188-11eb-9092-61d3596c7b18.png)

it opens like that in the browser as well, leading to a broken page

**Comment by Decimation** [comment]
This is normal behavior. The result is supposed to be the most accurate result link, not necessarily the search link (i.e. `https://iqdb.org/?url=...`. I have been considering adding the ability to open the search link, which is what I'm guessing you want?

> leading to a broken page

What do you mean by this?

**Comment by Xanawatt** [comment]
no, it's because of the http:https://
This page doesn't exist because when opened in a browser, the page gives http:https//yande.re/post/show/589623
Somewhere, it looks like you're appending http or something.

**Comment by Xanawatt** [comment]
btw, in regards to your assumption. I like what you did with the saucenao results with holding alt to get the other results. (It maybe could be applied to other search engines)

**Comment by Decimation** [comment]
Oh, woops, I didn't see that. 

You're correct, I append "http:" to IQDB's results. It turns out that some results from IQDB already have "http:" prefixes, which is why that bug occurred. I'll have a fix for this soon.

**Comment by Decimation** [comment]
@Xanawatt Ok, try v2.1.

**Comment by Xanawatt** [comment]
yup, worked perfectly! Thanks!

**Comment by Decimation** [comment]
Great! No problem.

Also:

> btw, in regards to your assumption. I like what you did with the saucenao results with holding alt to get the other results. (It maybe could be applied to other search engines)

It's actually used for all engines, so long as there are other results (that can be parsed).

**Comment by Xanawatt** [comment]
Ah, I see now. Nice!
