### ISSUE TITLE
Unhandled exception.

### ISSUE THREAD

**Issue by MitteDev** [Decimation/SmartImage#12]
C:\Users\Home\Desktop>SmartImage.exe
Unhandled exception. System.ArgumentOutOfRangeException: The new console window size would force the console buffer size to be too large. (Parameter 'height')
Actual value was 50.
   at System.ConsolePal.SetWindowSize(Int32 width, Int32 height)
   at System.Console.SetWindowSize(Int32 width, Int32 height)
   at SmartImage.Program.Main(String[] args)
   
   
   What is it?

**Comment by Decimation** [comment]
It looks like your console window was already big enough. I'll release a fix in a bit.

**Comment by Decimation** [comment]
Try the latest version, v2.0.2.

**Comment by MitteDev** [comment]
Thanks you!
<з
