### ISSUE TITLE
I can't configure the program 

### ISSUE THREAD

**Issue by VanTuz5** [Decimation/SmartImage#16]
I expose the settings so that the program search in Saucenao, Yandex and Google, but it starts searching everywhere.
And how should the program be configured so that it immediately opens search results in the browser?

**Comment by VanTuz5** [comment]
Did not work

**Comment by VanTuz5** [comment]
The problem is still the same - the settings are not saved, the program still searches everywhere

**Comment by VanTuz5** [comment]
If anything, I'm trying to use the program through the context menu.

**Comment by Decimation** [comment]
Configuration doesn't save across uses (for the time being). The next release will have this feature, though.

**Comment by VanTuz5** [comment]
ok, thanks

**Comment by Decimation** [comment]
if you're still interested, this has been implemented in [v2.1.2](https://github.com/Decimation/SmartImage/releases/tag/v2.1.2).

**Comment by VanTuz5** [comment]
thanks a lot
