### ISSUE TITLE
The browser is not open

### ISSUE THREAD

**Issue by lhj5426** [Decimation/SmartImage#17]
![image](https://user-images.githubusercontent.com/30548000/122668646-a2931500-d1eb-11eb-8bac-5afb1574d9bd.png)

That's the only way. No, then

**Comment by Decimation** [comment]
Did you specify trace.moe as a priority engine?

**Comment by Decimation** [comment]
Or do you mean it doesn't open when you press 0?

**Comment by lhj5426** [comment]
> Did you specify trace.moe as a priority engine?

I just drag the picture to the black box of the software, and I don't know how to set it. I didn't open the browser automatically as you demonstrated. How to set the browser to open automatically?

**Comment by lhj5426** [comment]
> Or do you mean it doesn't open when you press 0?
It's too much trouble to press the button. Wouldn't it be better to automatically open all the search results pages

**Comment by lhj5426** [comment]
> Or do you mean it doesn't open when you press 0?

https://github.com/Decimation/SmartImage/raw/master/Examples/Demo.gif

I want to automatically open the web page and use all search according to your demo. How do I set the parameters?

I didn't use the right button


I use this tool to pass parameters

https://github.com/hui-Zz/RunAny

SmartImage|O:\dupan\SmartImage.exe %getZz%

**Comment by Decimation** [comment]
Open the program like normal and press 2 to configure priority engines (engines whose results are opened in the browser).

![Screenshot 2021-06-21 025028](https://user-images.githubusercontent.com/4624891/122726428-99ca2f80-d23b-11eb-8bd9-5e99c3e1df13.png)

Select the engines whose results you want to open in the browser. In your case, you want trace.moe to open, so press 7, then press Escape to save.

![Screenshot 2021-06-21 025058](https://user-images.githubusercontent.com/4624891/122726481-a6e71e80-d23b-11eb-8f84-7c6650fbbdb5.png)

**Comment by lhj5426** [comment]
> Open the program like normal and press 2 to configure priority engines (engines whose results are opened in the browser).
> 
> ![Screenshot 2021-06-21 025028](https://user-images.githubusercontent.com/4624891/122726428-99ca2f80-d23b-11eb-8bd9-5e99c3e1df13.png)
> 
> Select the engines whose results you want to open in the browser. In your case, you want trace.moe to open, so press 7, then press Escape to save.
> 
> ![Screenshot 2021-06-21 025058](https://user-images.githubusercontent.com/4624891/122726481-a6e71e80-d23b-11eb-8f84-7c6650fbbdb5.png)
> 
> After that, results from trace.moe will open in your browser.

Thanks to the developer's patience and guide me to try it. Thank you.

**Comment by lhj5426** [comment]
![6666](https://user-images.githubusercontent.com/30548000/122795327-c93a7400-d2ef-11eb-9f95-39f93d1724c0.gif)
Which is useless? ? ?
It has always been this interface without any changes in 12345678, all of which are all over the interface.

Is it missing in my computer?
![image](https://user-images.githubusercontent.com/30548000/122795574-0b63b580-d2f0-11eb-97dd-f9a85e97354e.png)

**Comment by lhj5426** [comment]
> Are you using the number pad number keys? Those won't work

![image](https://user-images.githubusercontent.com/30548000/122843729-bdbc6c80-d332-11eb-9e51-2da676c52970.png)
The keyboard on both sides uses the difference, please help me thank you kai'fa'z

**Comment by Decimation** [comment]
![122843872-ff4d1780-d332-11eb-86ad-0a0ea94672e5](https://user-images.githubusercontent.com/4624891/122845396-4999ae80-d2c9-11eb-9303-a50a09bf753f.png)

Make sure you're using these number keys.

Also what is your system language?

**Comment by Decimation** [comment]
Any success?

**Comment by lhj5426** [comment]
> Any success?

I am really sorry to have no success.

**Comment by Decimation** [comment]
What keyboard are you using?

**Comment by lhj5426** [comment]
> What keyboard are you using?

Ordinary USB keyboard model Logitech G510

**Comment by lhj5426** [comment]
> What keyboard are you using?
I think it is not related to the keyboard hardware. All types of typing features are zheng'c.

**Comment by Decimation** [comment]
Try disabling RunAny. It may be interfering with reading keys.

**Comment by lhj5426** [comment]
> Try disabling RunAny. It may be interfering with reading keys.

![image](https://user-images.githubusercontent.com/30548000/122941356-e763ab00-d3a7-11eb-802b-ce6aa8a02851.png)

The problem found because the software you develop must run the ENG input method under the English input method and I use Chinese input method when entering the command. . .

Now I can return to the original question. I am really sorry for you.

**Comment by lhj5426** [comment]
Can you ask how to add context menu?

**Comment by Decimation** [comment]
Press number 4 in the main menu as seen here

![122726428-99ca2f80-d23b-11eb-8bd9-5e99c3e1df13.png](https://user-images.githubusercontent.com/4624891/122942656-fdd41d00-d33b-11eb-9845-2351da3116e1.png)

**Comment by Decimation** [comment]
Press number 4 in the main menu as seen here (in green)

![IMG_20210622_093112.jpg](https://user-images.githubusercontent.com/4624891/122943389-98ccf700-d33c-11eb-9066-2c1292bc8a02.jpg)

**Comment by lhj5426** [comment]
> > Can you ask how to add context menu?
> 
> Press number 4 in the main menu as seen here (in green)
> 
> ![IMG_20210622_093112.jpg](https://user-images.githubusercontent.com/4624891/122943389-98ccf700-d33c-11eb-9066-2c1292bc8a02.jpg)

![image](https://user-images.githubusercontent.com/30548000/122944837-b9339a80-d3aa-11eb-901e-91d2e224763e.png)

Thank you very much, I can now experience this tool you develop.

**Comment by lhj5426** [comment]
https://i.imgur.com/nC7l5MH.png  
This kind of search is not displayed in saucenao has a result, but it is not pixiv.

**Comment by Decimation** [comment]
> https://i.imgur.com/nC7l5MH.png  
> This kind of search is not displayed in saucenao has a result, but it is not pixiv.

There might be other results from SauceNao, one of which may be the Pixiv result. 

The number of other results found is displayed as seen here.

![Screenshot_20210622_101251.png](https://user-images.githubusercontent.com/4624891/122950905-763ddc80-d342-11eb-9fbc-3b14a9b5603e.png)

You can view the other results by pressing `Alt` and the result number. For example, pressing `Alt+0` would show the other results for result #0.
