### ISSUE TITLE
Future Linux version?

### ISSUE THREAD

**Issue by mknepper** [Decimation/SmartImage#19]
Just a suggestion, but I think something like this on Linux would be amazing. I'm not sure what would need to happen to make it a Linux release, but the community would probably help.

**Comment by Decimation** [comment]
I'd like to create a Linux version, but this would be a huge undertaking. SmartImage uses a lot of Windows API functions, and a Linux version would require writing the console interface, the context menu integration, and a myriad of other things to be compatible with Linux.

**Comment by Decimation** [comment]
@mknepper If you're still interested years later, there is now a cross-platform CLI build: [SmartImage.Rdx](https://github.com/Decimation/SmartImage/releases).

**Comment by Decimation** [comment]
cc @NaiveInvestigator since they expressed interest in my response.
