### ISSUE TITLE
SmartImage not opening from context menu

### ISSUE THREAD

**Issue by Xanawatt** [Decimation/SmartImage#2]
Hi, I placed the executable in my system %PATH% location (C:\) and then ran the command as administrator to add the context menu (SmartImage --ctx-menu). When I try to right click a file and click the SmartImage option, it just opens the default "How would you like to open this file" window. Is there a step I am missing? Did I place the executable in the right location?

**Comment by Decimation** [comment]
I'm aware of this issue. I'm trying to figure this out.

**Comment by Decimation** [comment]
This has been fixed in the most recent version. I had accidentally used my personal executable path in the registry command. It should work now!

**Comment by Xanawatt** [comment]
I get this error when running "SmartImage --ctx-menu" now:

`Unhandled` exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at SmartImage.Config.GetExecutableLocation()
   at SmartImage.Config.CreateBatchFile()
   at SmartImage.Config.AddToContextMenu()
   at SmartImage.Cli.<>c.<.cctor>b__20_3(String[] args)
   at SmartImage.Program.Main(String[] args)`

**Comment by Decimation** [comment]
Try the latest version.

**Comment by Xanawatt** [comment]
Alright, I get this now when I run the same thing:

× Could not locate SmartImage.exe in system path.
Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at SmartImage.Config.GetExecutableLocation()
   at SmartImage.Config.AddToContextMenu()
   at SmartImage.Cli.<>c.<.cctor>b__20_3(String[] args)
   at SmartImage.Program.Main(String[] args)

**Comment by Decimation** [comment]
`C:` is not included in the system `%PATH%` by default. `%PATH%` is an environment variable in Windows (I'm not sure if you know how environment variables work, but you can read about them [here](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10)).

I was planning on simplifying things by automatically adding the program's current directory to %PATH% eventually so users don't have to mess with it (it's not very user-friendly). I'll update it with this feature shortly.

**Comment by Xanawatt** [comment]
Ohhh, that makes sense. Now that I have done that, it works perfectly now!

**Comment by Decimation** [comment]
Great! Thanks for using SmartImage!
