### ISSUE TITLE
SmartImage doesn't open at all

### ISSUE THREAD

**Issue by LostCursor** [Decimation/SmartImage#20]
When I attempt to open any version of SmartImage.exe, this error shows up: (see attached).
![image_2021-12-01_200134](https://user-images.githubusercontent.com/17422580/144231017-5856d4ec-af85-4159-b10d-e2d41b759605.png)

**Comment by Decimation** [comment]
Do you have .NET 6 installed? Is your antivirus detecting anything?

**Comment by LostCursor** [comment]
My bad, I had to install .NET6 and run the program as an administrator. Thanks for the help!
