### ISSUE TITLE
Program crashes on opening

### ISSUE THREAD

**Issue by s0902rx** [Decimation/SmartImage#21]
The programs crashes on opening and displays messages for a millisecond if i spam open it.

Here's a video and screenshots of the messages.

https://user-images.githubusercontent.com/79232286/148838163-2a16c2d9-f254-42c6-9040-e05a8e4a5318.mp4

https://user-images.githubusercontent.com/79232286/148838554-1a6845cb-b159-4626-900b-55ff3e3a902d.png

https://user-images.githubusercontent.com/79232286/148838884-c8bb50f4-73b3-4325-ad1e-3f756242e32f.png

**Comment by sysxvx** [comment]
Installed .NET SKD x64 from this page https://dotnet.microsoft.com/en-us/download and it fixed it, the fact that the program closed instantly without being able to read the errors which appeared only sometimes and were different was weird.

**Comment by Decimation** [comment]
So I assume everything is working fine now?

**Comment by s0902rx** [comment]
Yep
