### ISSUE TITLE
"A fatal error occurred. The required library hostfxr.dll could not be found."

### ISSUE THREAD

**Issue by IJCS** [Decimation/SmartImage#23]
When I try to run it from cmd the latest version (v2.2.2) I get a message 
`A fatal error occurred. The required library hostfxr.dll could not be found `

I was recently cleaning things up on my PC and I may have broke some of the .Net.... but still the previous version was still working.

**Comment by Decimation** [comment]
Do you have .NET 6 installed?

**Comment by IJCS** [comment]
Yes, but I tried reinstalling it and was fixed. I'll assume I deleted something extra during maintenance.
