### ISSUE TITLE
NullReferenceException after image upload

### ISSUE THREAD

**Issue by Xanawatt** [Decimation/SmartImage#3]
For a select number of images, I am getting the error pictured below. The program then quits.
![image](https://user-images.githubusercontent.com/22943944/77025732-426a4f00-6968-11ea-8f72-c880e462ffa2.png)

**Comment by Decimation** [comment]
Try the latest build. Can you give more detail? What kind of images are they?

**Comment by Xanawatt** [comment]
The latest build did not fix the problem unfortunately. As far as I can tell, they are just regular .jpg files. They were .jiff files, but were just converted by changing the file extension. That shouldn't matter however because other conversions have worked fine with SmartImage.

**Comment by Decimation** [comment]
Could you share the images you used? It works for me when I change the file extension.

**Comment by Decimation** [comment]
Could you share the images you used? It works when I change the extensions.

**Comment by Xanawatt** [comment]
Here are three images that don't work. 
![73139](https://user-images.githubusercontent.com/22943944/77085886-59945580-69d7-11ea-8bd2-099549844b66.jpg)
![EO9YsYSU4AIS9Ii](https://user-images.githubusercontent.com/22943944/77085890-5ac58280-69d7-11ea-8779-bc74cd15814b.jpg)
![EPKTOBxVUAArWg3](https://user-images.githubusercontent.com/22943944/77085897-5bf6af80-69d7-11ea-85a9-00091e9e0ac2.jpg)

**Comment by Decimation** [comment]
The latest build should have this fixed.
