### ISSUE TITLE
Pass argument?

### ISSUE THREAD

**Issue by Inexpress** [Decimation/SmartImage#30]
I may be doing something wrong, but is there a way to pass an image to SmartImage as a command line argument in the new 3.0 version? Thanks.

**Comment by Decimation** [comment]
Yes, command line support is still WIP, but you can use the `-i` parameter as follows:

`SmartImage.exe -i <input>`

For example:
`.\SmartImage.exe -i 'C:\Users\Deci\Pictures\Art\Makima 1-3.png'`

**Comment by Inexpress** [comment]
Amazing, thank you for your rapid response and for this very useful tool! <3

**Comment by Decimation** [comment]
No problem! Feel free to reopen if you have any further questions.
