### ISSUE TITLE
Ascii2D Cloudflare protection

### ISSUE THREAD

**Issue by Decimation** [Decimation/SmartImage#31]
**Ascii2D** seems to have implemented Cloudflare protection which prevents scraping of its results. Cloudflare protection has to be circumvented or an alternative method of retrieving **Ascii2D** results is needed.

**Comment by neoOpus** [comment]
[FlareSolverr](https://github.com/FlareSolverr/FlareSolverr)

**Comment by Decimation** [comment]
It seems *Ascii2D* is working again.
