### ISSUE TITLE
clipboard feature

### ISSUE THREAD

**Issue by assg4** [Decimation/SmartImage#32]
is there any possibility of a feature about using this program with an image stored in the clipboard instead of saved images?

edit: i figured out i can paste regular images but i can't paste the ones i take from windows snaptool (win + shift + s)

**Comment by Decimation** [comment]
It seems the snipping tool has an undocumented clipboard format `PNG` which is the binary value of a `PNG` image. I successfully managed to read in the `PNG` image, so I should be able to implement this feature easily.

**Comment by Decimation** [comment]
The latest release, 3.0.1, implemented this.
