### ISSUE TITLE
windows 7

### ISSUE THREAD

**Issue by harryray33** [Decimation/SmartImage#38]
Does this work with Win 7?

Thanks

**Comment by Decimation** [comment]
~~It should work so long as you have .NET 7 installed. Try it and let me know.~~

**Comment by harryray33** [comment]
Thanks. It appears that .NET 7 isn't supported on Win 7. Is there any way round this?

Would an earlier release work?

**Comment by Decimation** [comment]
SmartImage build targets .NET 7 Windows 10. I can try to create a Windows 7 build.

**Comment by harryray33** [comment]
Thank you, a Windows 7 build would be great....

**Comment by harryray33** [comment]
Did you manage to do a Win 7 build?

Thanks

**Comment by Decimation** [comment]
Unfortunately, I cannot create a Windows 7 compatible build as it would require downgrading .NET and re-targeting the entire codebase. Windows 7 and Windows 8.1 support ended with [.NET 7](https://github.com/dotnet/core/issues/7556), which SmartImage uses.

**Comment by harryray33** [comment]
Thanks. Do you know if there is any other project comparable to this?

**Comment by Decimation** [comment]
Not that I'm aware of. Although I wouldn't normally recommend upgrading Windows, I would advise upgrading to Windows 10 at this point if you're able and willing.
