### ISSUE TITLE
Добавь функцию

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [Decimation/SmartImage#45]
1. when you do a search, it opens the browser with sites. I want to do it manually through MAIN. select it yourself, without automatically opening the site
2. doesn't show the checkboxes that I checked.

**Comment by Decimation** [comment]
### 1.
The results which are opened in the browser, configure **Priority Engines**. These are the engines whose results are opened in the browser. Simply select `None` in the options:

![2023-09-06_(15h57m06s)_z0VpzUo5sl](https://github.com/Decimation/SmartImage/assets/4624891/c1f56765-4568-48a7-b052-d252b1b2373f)


### 2.

Do you mean the configuration isn't saving?
