### ISSUE TITLE
GUI not uploading image

### ISSUE THREAD

**Issue by beakwood** [Decimation/SmartImage#46]
I'm using the GUI version, 4.0.0, and it's not uploading the image to the sources. But, when I use 3.0.4 it works correctly. Although, rarely, it too doesn't upload the image. I would have to wait a few minutes before retrying the search and it works. I even tried GUI on a fresh installation of Windows 11, and it still doesn't work. 

 Not only that, but I tried downloading the zip, to my surprise there were no EXE in the zip. Am I supposed to build the EXE someway?

**Comment by Decimation** [comment]
This is probably caused by the upload engine (_CatBox_ by default) timing out. Can you try out `v4.0.2`?

**Comment by beakwood** [comment]
I believe that was the case. I'm currently using v4.0.2 and it's working as intended.
