### ISSUE TITLE
Support fluffle.xyz

### ISSUE THREAD

**Issue by EndzE** [Decimation/SmartImage#55]
Would be nice.
They have an easy to implement api: https://fluffle.xyz/api/

**Comment by Decimation** [comment]
I have implemented **Fluffle**. Can you try out [v1.0.1-rdx](https://github.com/Decimation/SmartImage/releases/tag/v1.0.1-rdx)?

**Comment by EndzE** [comment]
> I have implemented **Fluffle**. Can you try out [v1.0.1-rdx](https://github.com/Decimation/SmartImage/releases/tag/v1.0.1-rdx)?

Works great, thanks!
