### ISSUE TITLE
Issue while opening

### ISSUE THREAD

**Issue by BedBug2479** [Decimation/SmartImage#8]
Everytime i open an img

----------Exception----------
Exception message: Exception of type 'SmartImage.Utilities.SmartImageException' was thrown.
Exception stack trace:    at SmartImage.RuntimeInfo.FindExecutableLocation(String exe)
   at SmartImage.RuntimeInfo.get_ExeLocation()
   at SmartImage.RuntimeInfo.get_AppFolder()
   at SmartImage.RuntimeInfo.get_IsAppFolderInPath()
   at SmartImage.Integration.Setup()
   at SmartImage.Program.Main(String[] args)
Source: SmartImage
HResult: -2146233088
Site: System.String FindExecutableLocation(System.String)

----------Config----------
Error adding config
----------Program Info----------
Version: 1.9.7.0
Crash log written to C:\Users\BedBug\Desktop\crash.log
Please file an issue and attach the crash log.

Press any key to continue...

**Comment by Decimation** [comment]
Where did you place the executable?
