### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by itsusmanmirza** [Decimation/SmartImage#9]
![SmartImage_VPIcMp15g1](https://user-images.githubusercontent.com/36538038/95914442-24aa7e80-0dbf-11eb-9774-c27b40d1ccf3.jpg)

**Comment by Decimation** [comment]
Try just using ImgOps for image upload. This seems to be an issue with Imgur.

**Comment by Decimation** [comment]
This should be fixed in the latest release **v1.9.8**.
